"""Canonical installed-runtime contracts for Ares releases.

This package deliberately owns installation and activation semantics, while
``hermes_cli.ares_candidate_store`` continues to own candidate custody and
authorization.
"""

from .contracts import (
    ACTIVATION_GRANT_SCHEMA,
    INSTALLED_RUNTIME_POINTER_SCHEMA,
    RUNTIME_IDENTITY_SCHEMA,
    ActivationGrant,
    InstalledRuntimePointer,
    ReleaseReference,
    RuntimeIdentity,
)
from .errors import AresRuntimeError
from .layout import AresRuntimeLayout
from .materializer import MaterializedRelease, materialize_candidate_release
from .activation import ActivationResult, ActivationState, AresReleaseActivator
from .resolver import AresRuntimeResolver, ResolvedRuntime
from .image import (
    RELEASE_MANIFEST_SCHEMA,
    RuntimeImage,
    stage_runtime_image,
    write_release_manifest,
)
from .collaboration import (
    BaselineResultV1,
    BlindWitness,
    ClosureProjector,
    ContextCompiler,
    ContextMaterializer,
    ContextPacketV1,
    ResolvedPolicyBasisV1,
    SealedInvocationV1,
    ContractBindings,
    ContractError,
    DesktopProductionApprovalController,
    DesktopProductionApprovalEnvelope,
    DesktopProductionApprovalWitnessProvider,
    FrozenReplayCorpusV1,
    closure_ui_projection,
    DaemonPermitReceiptAdapter,
    PermitBridgeOutcome,
    PermitBridgeState,
    EvidenceItemV1,
    FindingV1,
    HandoffPacketV1,
    MissionContractV1,
    RoleContractV1,
    SpecialistDescriptorV1,
    TestRequestV1,
    dispatcher_boundary,
    evaluation_ui_projection,
    freeze_replay_corpus,
    make_artifact,
    replay_mutations,
    specialist_descriptor_ref,
    validate_specialist_descriptor_set,
)
from .governed_context import (
    MANAGED_MODEL_CALL_KINDS,
    GovernedContextMaterializer,
    ManagedCallKind,
    ManagedMaterialization,
    MaterializationReceiptStore,
    MaterializedContextV1,
    MemoryRequirement,
    MemoryResolutionState,
    PersistedManagedMaterialization,
    SemanticMemoryObservationV1,
    SemanticMemoryWitnessedPort,
    plan_legacy_memory_import,
)

__all__ = [
    "ACTIVATION_GRANT_SCHEMA",
    "INSTALLED_RUNTIME_POINTER_SCHEMA",
    "RUNTIME_IDENTITY_SCHEMA",
    "ActivationGrant",
    "ActivationResult",
    "ActivationState",
    "AresReleaseActivator",
    "AresRuntimeResolver",
    "RELEASE_MANIFEST_SCHEMA",
    "AresRuntimeError",
    "AresRuntimeLayout",
    "InstalledRuntimePointer",
    "MaterializedRelease",
    "ReleaseReference",
    "RuntimeIdentity",
    "RuntimeImage",
    "ResolvedRuntime",
    "materialize_candidate_release",
    "stage_runtime_image",
    "write_release_manifest",
    "BaselineResultV1",
    "BlindWitness",
    "ClosureProjector",
    "ContextCompiler",
    "ContextMaterializer",
    "ContextPacketV1",
    "ResolvedPolicyBasisV1",
    "SealedInvocationV1",
    "ContractBindings",
    "ContractError",
    "DesktopProductionApprovalController",
    "DesktopProductionApprovalEnvelope",
    "DesktopProductionApprovalWitnessProvider",
    "FrozenReplayCorpusV1",
    "closure_ui_projection",
    "DaemonPermitReceiptAdapter",
    "PermitBridgeOutcome",
    "PermitBridgeState",
    "EvidenceItemV1",
    "FindingV1",
    "HandoffPacketV1",
    "MissionContractV1",
    "RoleContractV1",
    "SpecialistDescriptorV1",
    "TestRequestV1",
    "dispatcher_boundary",
    "evaluation_ui_projection",
    "freeze_replay_corpus",
    "make_artifact",
    "replay_mutations",
    "specialist_descriptor_ref",
    "validate_specialist_descriptor_set",
    "MANAGED_MODEL_CALL_KINDS",
    "GovernedContextMaterializer",
    "ManagedCallKind",
    "ManagedMaterialization",
    "MaterializationReceiptStore",
    "MaterializedContextV1",
    "MemoryRequirement",
    "MemoryResolutionState",
    "PersistedManagedMaterialization",
    "SemanticMemoryObservationV1",
    "SemanticMemoryWitnessedPort",
    "plan_legacy_memory_import",
]
