"""V2 consumer tests against actual current profile-runtime owner output.

The fixture is generated by tests/owner_integration/profile_runtime_fixture.rs.
Owner readback here is a disposable qualification fixture, not authentication
or evidence that a live profile-runtime service has been activated.
"""
from __future__ import annotations

import copy
import json
from pathlib import Path

import pytest

from ares_runtime.collaboration import (
    ContractError,
    ContextMaterializer,
    ResolvedPolicyBasisV1,
    ResolvedPolicyBasisV2,
)
from ares_runtime.governed_context import MANAGED_MODEL_CALL_KINDS, MemoryRequirement
from tests.ares_runtime.test_governed_context_materialization import authorize, materialize


OWNER = json.loads(
    (Path(__file__).parent / "fixtures" / "profile_runtime_v2_owner.json").read_text()
)


def resolve(ref, value_digest):
    for name in ("v1", "v2", "other_task_v2"):
        owner = OWNER[name]
        if ref == owner["basis_ref"] and value_digest == "blake3:" + owner["basis_digest"]:
            return copy.deepcopy(owner)
    return None


def basis():
    return ResolvedPolicyBasisV2.from_profile_runtime(
        OWNER["v2"], expected_task_ref="task:1", resolve_owner=resolve
    )


@pytest.mark.parametrize("call_kind", MANAGED_MODEL_CALL_KINDS)
def test_v2_identity_survives_real_materialization_persistence_and_egress(call_kind):
    current = basis()
    result, memory, owner, current = materialize(
        basis=current, owner=OWNER["v2"], call_kind=call_kind,
        memory_requirement=MemoryRequirement.NOT_REQUIRED, memory_query=None,
    )
    sealed = result.sealed_invocation.to_dict()
    receipt = result.materialization.to_dict()
    assert sealed["basis_ref"] == owner["basis_ref"]
    assert sealed["basis_digest"] == "blake3:" + owner["basis_digest"]
    assert receipt["policy_basis_ref"] == owner["basis_ref"]
    assert receipt["policy_basis_digest"] == sealed["basis_digest"]
    assert authorize(result, memory, owner, current) == result.serialized_request
    with pytest.raises(ContractError, match="POLICY_BASIS_MISMATCH"):
        authorize(result, memory, OWNER["other_task_v2"], current)


def test_v1_stays_explicit_and_v2_does_not_downgrade_to_the_inner_identity():
    legacy = ResolvedPolicyBasisV1.from_profile_runtime(OWNER["v1"], resolve_owner=resolve)
    assert legacy.to_dict()["basis_ref"] == OWNER["v1"]["basis_ref"]
    assert basis().to_dict()["basis_ref"] != legacy.to_dict()["basis_ref"]
    assert OWNER["v2"]["owner_projection"]["basis_ref"] == OWNER["other_task_v2"]["owner_projection"]["basis_ref"]
    assert OWNER["v2"]["basis_ref"] != OWNER["other_task_v2"]["basis_ref"]
    with pytest.raises(ContractError):
        ResolvedPolicyBasisV1.from_profile_runtime(OWNER["v2"], resolve_owner=resolve)
    with pytest.raises(ContractError):
        ResolvedPolicyBasisV2.from_profile_runtime(
            OWNER["v1"], expected_task_ref="task:1", resolve_owner=resolve
        )


def test_v2_requires_the_expected_task_and_a_current_owner_readback():
    with pytest.raises(ContractError, match="POLICY_TASK_MISMATCH"):
        ResolvedPolicyBasisV2.from_profile_runtime(
            OWNER["other_task_v2"], expected_task_ref="task:1", resolve_owner=resolve
        )
    with pytest.raises(ContractError, match="OWNER_POLICY_UNAVAILABLE"):
        ResolvedPolicyBasisV2.from_profile_runtime(
            OWNER["v2"], expected_task_ref="task:1", resolve_owner=lambda *_: None
        )
    with pytest.raises(ContractError, match="OWNER_POLICY_MISMATCH"):
        ResolvedPolicyBasisV2.from_profile_runtime(
            OWNER["v2"], expected_task_ref="task:1",
            resolve_owner=lambda *_: OWNER["other_task_v2"],
        )


@pytest.mark.parametrize("mutation", ["task", "reference", "digest", "unknown", "nested_unknown"])
def test_v2_tamper_cannot_acquire_owner_verification(mutation):
    raw = copy.deepcopy(OWNER["v2"])
    if mutation == "task":
        raw["owner_projection"]["task_ref"] = "task:changed"
    elif mutation == "reference":
        raw["basis_ref"] = OWNER["other_task_v2"]["basis_ref"]
    elif mutation == "digest":
        raw["basis_digest"] = OWNER["other_task_v2"]["basis_digest"]
    elif mutation == "unknown":
        raw["authorizes_egress"] = True
    else:
        raw["owner_projection"]["authorizes_egress"] = True
    with pytest.raises(ContractError):
        ResolvedPolicyBasisV2.from_profile_runtime(
            raw, expected_task_ref="task:1", resolve_owner=resolve
        )


def test_serialized_v2_is_evidence_only_and_preserves_exact_owner_wire_fields():
    current = basis()
    assert current.to_dict()["owner_projection"] == OWNER["v2"]
    replayed = ResolvedPolicyBasisV2.parse(current.to_dict())
    assert not replayed.owner_verified
    with pytest.raises(ContractError, match="OWNER_POLICY_UNAVAILABLE"):
        ContextMaterializer._owner_payload(replayed)
    with pytest.raises(ContractError):
        ResolvedPolicyBasisV1.parse(current.to_dict())


@pytest.mark.parametrize("value", [None, 10**63, True, ["a" * 64], "bad", "a" * 63])
def test_v2_digest_requires_an_exact_owner_string(value):
    raw = copy.deepcopy(OWNER["v2"])
    raw["basis_digest"] = value
    with pytest.raises(ContractError, match="INVALID_DIGEST"):
        ResolvedPolicyBasisV2.from_profile_runtime(
            raw, expected_task_ref="task:1", resolve_owner=resolve
        )


def test_owner_callback_cannot_mutate_the_original_v2_request_into_agreement():
    raw = copy.deepcopy(OWNER["v2"])

    def mutate_original(*_):
        raw["owner_projection"]["source_revision"] = "source:changed"
        return raw

    with pytest.raises(ContractError, match="OWNER_POLICY_MISMATCH"):
        ResolvedPolicyBasisV2.from_profile_runtime(
            raw, expected_task_ref="task:1", resolve_owner=mutate_original
        )
