#!/usr/bin/env python3
"""Generate and verify the derived mobile protocol manifest."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_DIR = ROOT / "tui_gateway" / "protocol" / "schemas"
DEFAULT_MANIFEST = ROOT / "apps" / "shared" / "src" / "protocol" / "generated" / "mobile-protocol-manifest.json"
DEFAULT_TYPES = DEFAULT_MANIFEST.with_name("mobile-protocol.ts")


def build_manifest() -> dict:
    schemas = []
    for path in sorted(SCHEMA_DIR.glob("*.json")):
        raw = path.read_bytes()
        schemas.append(
            {
                "name": path.name,
                "bytes": len(raw),
                "sha256": hashlib.sha256(raw).hexdigest(),
            }
        )
    return {
        "schema": "AresMobileProtocolManifestV1",
        "protocol_revision": 2,
        "schemas": schemas,
    }


def write_manifest(path: Path, manifest: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def build_typescript(manifest: dict) -> str:
    digest = hashlib.sha256(
        json.dumps(manifest, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()
    return f'''// Generated by scripts/generate_mobile_protocol.py. Do not edit.
export const MOBILE_PROTOCOL_REVISION = {manifest["protocol_revision"]} as const
export const MOBILE_PROTOCOL_SCHEMA_DIGEST = "{digest}" as const

export interface GatewayCapabilities {{
  session_observe_v1: boolean
  session_snapshot_v1: boolean
  event_cursor_v1: boolean
  bounded_replay_v1: boolean
  session_control_lease_v1: boolean
  write_idempotency_v1: boolean
  mobile_surface_v1: boolean
}}

export interface GatewayReadyV2 {{
  protocol_revision: typeof MOBILE_PROTOCOL_REVISION
  schema_digest: string
  host_identity_digest: string
  runtime_id: string
  capabilities: GatewayCapabilities
}}

export interface SessionOwnerScope {{
  host_id: string
  connection_id: string
  profile: string
  session_id: string
  lineage_root_id: string
  runtime_id: string
}}

export interface SessionEventEnvelopeV1 {{
  host_id: string
  connection_id: string
  profile: string
  session_id: string
  lineage_root_id: string
  runtime_id: string
  revision: number
  event_id: string
  type: string
  payload?: Record<string, unknown>
  critical?: boolean
}}

export interface SessionSnapshotV1 {{
  scope: SessionOwnerScope
  schema_version: 1
  revision: number
  status: string
  transcript_tail: unknown[]
  transcript_cursor: string | null
  pending_requests: unknown[]
  controller: Record<string, unknown>
}}

export interface SessionControlLeaseV1 {{
  host_id: string
  profile: string
  session_id: string
  runtime_id: string
  principal_id: string
  controller_instance_id: string
  generation: number
  fencing_token: string
  expires_at: number
}}

export interface MutationOutcomeScopeV1 {{
  host_id: string
  profile: string
  session_key: string
  principal_id: string
}}

export interface MutationOutcomeV1 {{
  scope: MutationOutcomeScopeV1
  method: string
  idempotency_key: string
  payload_digest: string
  state: 'in_progress' | 'completed' | 'failed' | 'indeterminate'
  result: Record<string, unknown> | null
  error: Record<string, unknown> | null
  created_at: number
  updated_at: number
}}
'''


def write_types(path: Path, manifest: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(build_typescript(manifest), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--types", type=Path, default=DEFAULT_TYPES)
    args = parser.parse_args()
    if args.check == args.write:
        parser.error("choose exactly one of --check or --write")
    expected = build_manifest()
    if args.write:
        write_manifest(args.manifest, expected)
        write_types(args.types, expected)
        print(f"wrote {args.manifest} and {args.types}")
        return 0
    if not args.manifest.is_file():
        print(f"stale manifest: missing {args.manifest}")
        return 1
    try:
        actual = json.loads(args.manifest.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        print(f"stale manifest: unreadable {args.manifest}: {exc}")
        return 1
    if actual != expected:
        print(f"stale manifest: {args.manifest}")
        return 1
    if not args.types.is_file() or args.types.read_text(encoding="utf-8") != build_typescript(expected):
        print(f"stale types: {args.types}")
        return 1
    print(f"manifest current: {args.manifest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
